#!/usr/bin/perl
#
# New Sensortagd
# trying to make it better

$debug = 1;
if (!$debug) {
  use Proc::Daemon;
  $pid = Proc::Daemon::Init;
  exit if $pid;
}



use Config::Simple;

Config::Simple->import_from('./sensortagd.cfg', \%Config);

my $mqttserver= $Config{"Mqttserver"};
my $sensorline = $Config{"Sensors"};
my $locationline=$Config{"Locations"};
my $hostname = `hostname -f`;
my $site = $Config{"Site"};
chomp $hostname;

if ($mqttserver) {
  $mqttpub = "mosquitto_pub -h $mqttserver -p 1883 ";
  system("$mqttpub -t /$site/$hostname/sensortagd/status -m started");
}

my $i=0;
while ($sensorline->[$i]) {
  $sensors{$sensorline->[$i]} = 1;
  $location{$sensorline->[$i]} = $locationline->[$i];
  $sensorcount++;
  $i++;
}


$interface = $Config{"Interface"};


$sleeptime = 60;

$out = `hciconfig $interface down`;
$out = `hciconfig $interface up`;

$GAP_DEVICE_ID="0x12";

$BAROMETER_DATA_UUID = "f000aa41";
$BAROMETER_CONF_UUID = "f000aa42";
$BAROMETER_CALI_UUID = "f000aa43";

$HUMIDITY_DATA_UUID  = "f000aa21";
$HUMIDITY_CONF_UUID  = "f000aa22";

$ACCELEROMETER_DATA_UUID = "f000aa11";
$ACCELEROMETER_CONF_UUID = "f000aa12";

$IRTEMPERATURE_DATA_UUID = "f000aa01";
$IRTEMPERATURE_CONF_UUID = "f000aa02";


while (!$found) {
  foreach $addr (keys %sensors) {
    # Check if sensortag is alive
    #
    my $thisid = &GetDeviceId($addr);
    my $failcount = 0;
    while (!$thisid && $failcount < 10) {
      $thisid = &GetDeviceId($addr);
      sleep 5;
      $failcount++;
    }
    if ($thisid) {
      # get characteristics
      &readCharacteristics($addr);
      $alive{$addr} = $thisid;
      $location{$thisid} = $location{$addr};
      $found = 1;
    }
  }
}

# calibrate Barometer
# foreach $addr (keys %alive) {
  # &calibrateBarometer($addr); # no longer needed here
  # say Hello to server
# }

$count=1;
# Main loop
while (1) {
  my $loopstart = time;
  foreach $addr (keys %alive) {
    my ($temp1,$pres) = &readBarometricPressure($addr);
    my ($temp2,$humid) = &readHumidity($addr);
    my ($temp3,$target) = &readIRTemperature($addr);
    my $temp;
    if ($temp1 && $temp2 && $temp3) {
      $temp = ($temp1+$temp2+$temp3)/3.0;
    } elsif ($temp1) {
      $temp = $temp1;
    } elsif ($temp2) {
      $temp = $temp2;
    } elsif ($temp3) {
      $temp = $temp3;
    } else {
      $temp = 0;
    }
    # ($x,$y,$z) = &readGravity($addr);
    if ($debug) {
	    print "$pres hPa\n";
	    print "$humid %\n";
	    print "$temp1 °C $temp2 °C $temp3 °C $temp° C\n";
	    print "\n";
    }
    $count++;
    &sendToServer($count,$alive{$addr},$pres,$humid,$temp,$target);
  }
  my $howlong =  $sleeptime - (time - $loopstart);
  sleep $howlong if ($howlong > 0);
}


exit;

sub GetDeviceId {
  my $this = shift;

  my $out= `gatttool -i $interface -b $this --char-read --handle=$GAP_DEVICE_ID`;
  # Characteristic value/descriptor: 16 54 c3 00 00 29 6a bc
  if ($out =~ /:\s+([0-9a-fA-F ]+)$/) {
    my $id = $1;
    $id =~ s/ 00 00 //;
    $id =~ s/ //g;
    print "$id\n" if $debug;
    return $id;
  } else {
    return undef;
  }
}

sub calibrateBarometer {
  my $addr = shift;

  my $barometerCaliHandle = &getHandle($addr,$BAROMETER_CALI_UUID);
  my $barometerConfHandle = &getHandle($addr,$BAROMETER_CONF_UUID);

  $out = `gatttool -i $interface -b $addr --char-write-req --handle=$barometerConfHandle -n 02`;
  print $out if $debug;

  $out= `gatttool -i $interface -b $addr --char-read --handle=$barometerCaliHandle`;
  print $out if $debug;

  if ($out =~ /:\s+(..) (..) (..) (..) (..) (..) (..) (..) (..) (..) (..) (..) (..) (..) (..) (..)/) {
    $calib{$addr,1} = (hex($2) << 8) + hex($1);
    $calib{$addr,2} = (hex($4) << 8) + hex($3);
    $calib{$addr,3} = (hex($6) << 8) + hex($5);
    $calib{$addr,4} = (hex($8) << 8) + hex($7);

    $calib{$addr,5} = unpack('s', pack('S', hex($10 . $9)));
    $calib{$addr,6} = unpack('s', pack('S', hex($12 . $11)));
    $calib{$addr,7} = unpack('s', pack('S', hex($14 . $13)));
    $calib{$addr,8} = unpack('s', pack('S', hex($16 . $15)));

    $barometerCalibrated{$addr} = 1;
  }
}



sub readCharacteristics {
  my $this = shift;

  open(F,"gatttool -i $interface -b $this --characteristics|");
  while (<F>) {
    # handle = 0x0002, char properties = 0x02, char value handle = 0x0003, uuid = 00002a00-0000-1000-8000-00805f9b34fb
    /char value handle = 0x([0-9a-fA-F]+),.*uuid = ([0-9a-fA-F]+)/;
    $uuid{$this,$2}=$1;
    $uuid{"generic",$2}=$1;
  }
  close F;
}

sub readIRTemperature {
  my $addr = shift;

  my $irtemperatureConfHandle = &getHandle($addr,$IRTEMPERATURE_CONF_UUID);
  my $irtemperatureDataHandle = &getHandle($addr,$IRTEMPERATURE_DATA_UUID);

  `gatttool -i $interface -b $addr --char-write-req --handle=$irtemperatureConfHandle --value=01`;
  my $out= `gatttool -i $interface -b $addr --char-read --handle=$irtemperatureDataHandle`;
  print $out if $debug;

  if ($out =~ /:\s+00 00 00 00/) {
    `gatttool -i $interface -b $addr --char-write-req --handle=$irtemperatureConfHandle --value=01`;
    $out= `gatttool -i $interface -b $addr --char-read --handle=$irtemperatureDataHandle`;
    print $out if $debug;
  }

  `gatttool -i $interface -b $addr --char-write-req --handle=$irtemperatureConfHandle --value=00`;
  if ($out =~ /:\s+00 00 00 00/) {
    return undef,undef;
  }

  # [5C:31:3E:87:AE:E1][LE]> char-read-hnd 0x25
  # Characteristic value/descriptor: b5 fe fc 0a


  if ($out =~ /:\s+(..) (..) (..) (..)/) {
    # calculate Temperature
    my $temp = ((hex($4) << 8) + hex($3)) / 128.0;
    # my $temp = unpack('s', pack('S', hex($4 . $3))) / 128.0;
    my $targetRaw = unpack('s', pack('S', hex($2 . $1)));

    my $Vobj = 1.5625e-7 * $targetRaw;
    my $tdie2 = $temp + 273.15;
    my $S = 6.4e-14 * (1 + 1.75e-3 * ($tdie2 - 298.15) - 1.678e-5 * ($tdie2 - 298.15)**2);
    my $Vos = -2.94e-5 - 5.7e-7*($tdie2 - 298.15) + 4.63e-9*($tdie2 - 298.15)**2;
    my $N = $Vobj - $Vos + 13.4*($Vobj - $Vos)**2;
    my $tObj = ($tdie2**4 + $N/$S)**0.25 - 273.15;

    print "Die temp = " . $temp . "  Target temp = " . $tObj . "\n" if $debug;

    return $temp,$tObj;
  }
  return undef,undef;
}

# Barometric Pressure
sub readBarometricPressure {
  my $addr = shift;

  if (! $barometerCalibrated{$addr}) {
    &calibrateBarometer($addr);
  }

  if (! $barometerCalibrated{$addr}) {
    return undef,undef;
  }

  my $barometerConfHandle = &getHandle($addr,$BAROMETER_CONF_UUID);
  my $barometerDataHandle = &getHandle($addr,$BAROMETER_DATA_UUID);

  `gatttool -i $interface -b $addr --char-write-req --handle=$barometerConfHandle --value=01`;
  my $out= `gatttool -i $interface -b $addr --char-read --handle=$barometerDataHandle`;
  print $out if $debug;

  if ($out =~ /:\s+00 00 00 00/) {
    `gatttool -i $interface -b $addr --char-write-req --handle=$barometerConfHandle --value=01`;
    $out= `gatttool -i $interface -b $addr --char-read --handle=$barometerDataHandle`;
    print $out if $debug;
  }

  `gatttool -i $interface -b $addr --char-write-req --handle=$barometerConfHandle --value=00`;
  if ($out =~ /:\s+00 00 00 00/) {
    return undef,undef;
  }

  if ($out =~ /:\s+(..) (..) (..) (..)/) {
  # calculate Temperature
    my $pressRaw= (hex($4) << 8) + hex($3);
    my $tempRaw = unpack('s', pack('S', hex($2 . $1)));
    my $tmp2 = ((($calib{$addr,1} * $tempRaw)/0x100 + ($calib{$addr,2} * 0x40 )) * 100) / 0x10000;
    my $temperature = ($tmp2 / 100.0);
    print "Temp = " . ($tmp2 / 100.0) . " C\n" if $debug;

  # calculate Pressure
    my $S=$calib{$addr,3}+(($calib{$addr,4}*$tempRaw)/0x20000)+(((($calib{$addr,5}*$tempRaw)/0x8000)*$tempRaw)/0x80000);
    my $O=$calib{$addr,6}*0x4000+(($calib{$addr,7}*$tempRaw)/8)+(((($calib{$addr,8}*$tempRaw)/0x8000)*$tempRaw)/16);
    my $pressure = (($S*$pressRaw+$O)/0x4000) / 100.0;

    print "Pressure = " . $pressure . " hPa\n" if $debug;
    return $temperature,$pressure;
  } else {
    return undef,undef;
  }
}

sub readHumidity {
  my $addr = shift;

  my $humidityConfHandle = &getHandle($addr,$HUMIDITY_CONF_UUID);
  my $humidityDataHandle = &getHandle($addr,$HUMIDITY_DATA_UUID);

  `gatttool -i $interface -b $addr --char-write-req --handle=$humidityConfHandle -n 01`;
  $out= `gatttool -i $interface -b $addr --char-read --handle=$humidityDataHandle`;
  `gatttool -i $interface -b $addr --char-write-req --handle=$humidityConfHandle -n 00`;

  if ($out =~ /:\s+(..) (..) (..) (..)/) {
    $templsb = hex($1);
    $tempmsb = hex($2);
    $humlsb = hex($3);
    $hummsb = hex($4);

    if ($templsb == 0 &&
	$tempmsb == 0 &&
	$humlsb == 0 &&
	$hummsb == 0) {
      return undef,undef;
    }

    $temp = -46.85 + 175.72/65536 * (($tempmsb << 8) + $templsb);
    $humraw = (($hummsb << 8) + $humlsb) & ~0x0003;
    $hum = -6.0 + 125.0/65536 * $humraw;

    print "Temp = $temp\n" if $debug;
    print "Hum  = $hum \%\n" if $debug;
    return $temp,$hum;
  } else {
    print $out if $debug;
    return undef,undef;
  }
}

sub readGravity {
  my $addr = shift;

  my $accelConfHandle = &getHandle($addr,$ACCELEROMETER_CONF_UUID);
  my $accelDataHandle = &getHandle($addr,$ACCELEROMETER_DATA_UUID);

  `gatttool -i $interface -b $addr --char-write-req --handle=$accelConfHandle -n 01`;
  my $out= `gatttool -i $interface -b $addr --char-read --handle=$accelDataHandle`;
  print $out if $debug;
  `gatttool -i $interface -b $addr --char-write-req --handle=$accelConfHandle -n 00`;
  if ($out =~ /:\s+(..) (..) (..)/) {
    my $x = (unpack('c', pack('C', hex($1)))) / (64.0/4.0);
    my $y = (unpack('c', pack('C', hex($2)))) / (64.0/4.0);
    my $z = (unpack('c', pack('C', hex($3)))) / (64.0/4.0);

    print "x=$x y=$y z=$z\n" if $debug;
    return sprintf("%.2f",$x),sprintf("%.2f",$y),sprintf("%.2f",$z);
  } else {
    return undef,undef,undef;
  }
}

sub getHandle {
  my $thisaddr = shift;
  my $thisuuid = shift;

  if ($uuid{$thisaddr,$thisuuid}) {
    return "0x" . $uuid{$thisaddr,$thisuuid};
  } else {
    return "0x" . $uuid{"generic",$thisuuid};
  }
}

sub sendToServer {
  my $c = shift;
  my $id = shift;
  my $pres = shift;
  my $hum  = shift;
  my $temp = shift;
  my $target = shift;

  my $node = "1.$id";
  my $spres, $stemp, $shum, $starget;



  if ($target) {
    if ($mqttpub) {
      my $path = "/$site/" . $location{$id} . "/target/temperature";
      system("$mqttpub -t $path -m $target");
    }
  }

  if ($pres) {
    if ($mqttpub) {
      my $path = "/$site/" . $location{$id} . "/airpressure";
      system("$mqttpub -t $path -m $pres");
    }
  }

  if ($hum) {
    if ($mqttpub) {
      my $path = "/$site/" . $location{$id} . "/humidity";
      system("$mqttpub -t $path -m $hum");
    }
  }

  if ($temp) {
    if ($mqttpub) {
      my $path = "/$site/" . $location{$id} . "/temperature";
      system("$mqttpub -t $path -m $temp");
    }
  }
}
